//  Sigma.getHistory module

//  History sent by the server
module.exports = function () {
  Sigma.socket.on('history', function (data) {
    //  If not empty
    if (data.empty) {
      var title = 'Welcome here pioneer!',
          content = 'It seems that you are the very first person on that channel. Please sign in or sign up.';
      Sigma.addContent(false, undefined, title, content, 'generated by Sigma', false);
    } else {
      //  Populate main div with the DOM content sent by the server
      data.documents.forEach(function (document) {
        Sigma.addContent(document.html, document._id);
      });
    }
    //  Keep track of channel emptiness
    Sigma.asyncUserAndHistoryState.channelIsEmpty = data.empty;
    //  Check if localStorage module was loaded too and set argument for empty channel
    Sigma.asyncUserAndHistoryState.check();
    //  Get images sources
    Sigma.loadResponsiveImages();
  });
};